import React, { useState, useEffect } from 'react';
import { 
  Box, 
  Paper, 
  Typography, 
  TextField, 
  Select, 
  MenuItem, 
  FormControl, 
  InputLabel, 
  Button, 
  Divider,
  IconButton,
  Grid,
  CircularProgress
} from '@mui/material';
import { LucideArrowLeft, LucideSave, LucideZap, LucideSettings, LucideActivity } from 'lucide-react';
import * as automationApi from '../../services/automationApi';
import { useNotifications } from '../../context/NotificationContext';

const textFieldStyle = {
  mb: 3,
  '& .MuiOutlinedInput-root': {
    borderRadius: '12px',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    '& fieldset': { borderColor: 'rgba(255, 255, 255, 0.1)' },
    '&:hover fieldset': { borderColor: 'var(--primary-color)' },
    '&.Mui-focused fieldset': { borderColor: 'var(--primary-color)' },
  },
  '& .MuiInputLabel-root': { color: 'var(--text-muted)' },
  '& .MuiInputLabel-root.Mui-focused': { color: 'var(--primary-color)' },
  '& .MuiInputBase-input': { color: 'var(--text-color)' },
};

const selectStyle = {
  backgroundColor: 'rgba(255, 255, 255, 0.03)',
  borderRadius: '12px',
  '& .MuiOutlinedInput-notchedOutline': {
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  '&:hover .MuiOutlinedInput-notchedOutline': {
    borderColor: 'var(--primary-color)',
  },
  '&.Mui-focused .MuiOutlinedInput-notchedOutline': {
    borderColor: 'var(--primary-color)',
  },
  color: 'var(--text-color)',
};

const AutomationBuilder = ({ onBack, onSaved }) => {
  const { addNotification } = useNotifications();
  const [loading, setLoading] = useState(false);

  // Form State
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  
  // Trigger config
  const [triggerEntity, setTriggerEntity] = useState('OPPORTUNITY');
  const [triggerEvent, setTriggerEvent] = useState('STAGE_CHANGED');
  const [triggerStageValue, setTriggerStageValue] = useState('CLOSED_WON');

  // Action config
  const [actionType, setActionType] = useState('CREATE_TASK');
  const [taskTitle, setTaskTitle] = useState('Follow up on won deal');
  const [taskDesc, setTaskDesc] = useState('Send onboarding materials and schedule a kickoff call.');

  // FCM Action config
  const [fcmTargetType, setFcmTargetType] = useState('TOPIC');
  const [fcmTargetValue, setFcmTargetValue] = useState('');
  const [fcmTitle, setFcmTitle] = useState('Automated Notification');
  const [fcmBody, setFcmBody] = useState('Notification generated by Automation Rule');

  const handleSave = async () => {
    if (!name) {
      addNotification('Please enter a name for the automation', 'error');
      return;
    }

    const payload = {
      name,
      description,
      isActive: true,
      triggerEntity,
      triggerEvent,
      triggerConfig: { field: 'stage', value: triggerStageValue },
      actionType,
      actionConfig: actionType === 'CREATE_TASK' 
        ? { title: taskTitle, description: taskDesc }
        : { targetType: fcmTargetType, targetValue: fcmTargetValue, title: fcmTitle, body: fcmBody }
    };

    try {
      setLoading(true);
      await automationApi.createAutomationRule(payload);
      addNotification('Automation rule created successfully!', 'success');
      onSaved();
    } catch (err) {
      addNotification('Failed to save automation rule', 'error');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Box sx={{ p: { xs: 2, md: 4 }, maxWidth: 1000, margin: '0 auto' }}>
      {/* Header Area */}
      <Box sx={{ 
        display: 'flex', 
        justifyContent: 'space-between', 
        alignItems: 'center', 
        mb: 4,
        position: 'sticky',
        top: 0,
        zIndex: 10,
        backgroundColor: 'var(--background-color)',
        py: 2
      }}>
        <Button 
          startIcon={<LucideArrowLeft size={18} />}
          onClick={onBack}
          sx={{ color: 'var(--text-muted)', textTransform: 'none', '&:hover': { color: 'var(--text-color)' } }}
        >
          Back to Automations
        </Button>
        <Button 
          variant="contained" 
          startIcon={loading ? <CircularProgress size={18} color="inherit" /> : <LucideSave size={18} />}
          onClick={handleSave}
          disabled={loading}
          sx={{ 
            bgcolor: 'var(--primary-color)',
            px: 4,
            py: 1,
            borderRadius: '12px',
            textTransform: 'none',
            boxShadow: '0 8px 16px rgba(124, 105, 239, 0.3)',
            '&:hover': { bgcolor: 'var(--primary-hover)' }
          }}
        >
          {loading ? 'Saving...' : 'Save Rule'}
        </Button>
      </Box>

      {/* Main Content Area */}
      <Box sx={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
        {/* Basic Info Section */}
        <Paper elevation={0} sx={{ 
          p: 3, 
          borderRadius: '24px', 
          bgcolor: 'rgba(255, 255, 255, 0.02)',
          border: '1px solid rgba(255, 255, 255, 0.05)',
          backdropFilter: 'blur(10px)'
        }}>
          <Typography variant="h6" sx={{ mb: 3, fontWeight: 600, display: 'flex', alignItems: 'center', gap: 1.5 }}>
            <LucideSettings size={20} color="var(--primary-color)" />
            Rule Overview
          </Typography>
          <Grid container spacing={3}>
            <Grid item xs={12} md={6}>
              <TextField 
                fullWidth 
                label="Rule Name" 
                placeholder="e.g., Onboarding task for won deals" 
                value={name}
                onChange={e => setName(e.target.value)}
                sx={textFieldStyle}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField 
                fullWidth 
                label="Description (Optional)" 
                placeholder="What does this rule do?" 
                value={description}
                onChange={e => setDescription(e.target.value)}
                multiline
                rows={1}
                sx={textFieldStyle}
              />
            </Grid>
          </Grid>
        </Paper>

        {/* Logic Flow Grid */}
        <Grid container spacing={3} alignItems="center">
          {/* WHEN (Trigger) */}
          <Grid item xs={12} md={5}>
            <Paper elevation={0} sx={{ 
              p: 4, 
              borderRadius: '24px', 
              bgcolor: 'rgba(124, 105, 239, 0.05)',
              border: '1px solid rgba(124, 105, 239, 0.1)',
              position: 'relative',
              minHeight: 340
            }}>
              <Box sx={{ 
                position: 'absolute', 
                top: -12, 
                left: 24, 
                bgcolor: 'var(--primary-color)', 
                px: 1.5, 
                py: 0.5, 
                borderRadius: '8px',
                color: 'white',
                fontSize: '0.75rem',
                fontWeight: 800,
                letterSpacing: 1
              }}>
                WHEN
              </Box>
              <Typography variant="h6" sx={{ mb: 1, fontWeight: 700 }}>Configure Trigger</Typography>
              <Typography variant="body2" sx={{ mb: 3, color: 'var(--text-muted)' }}>Choose the event that starts this automation.</Typography>

              <FormControl fullWidth sx={{ mb: 3 }}>
                <InputLabel sx={{ color: 'var(--text-muted)' }}>Entity Type</InputLabel>
                <Select
                  label="Entity Type"
                  value={triggerEntity}
                  onChange={e => setTriggerEntity(e.target.value)}
                  sx={selectStyle}
                  MenuProps={{ PaperProps: { sx: { bgcolor: '#1b2436' } } }}
                >
                  <MenuItem value="OPPORTUNITY">Opportunity (Deal)</MenuItem>
                </Select>
              </FormControl>

              <FormControl fullWidth sx={{ mb: 3 }}>
                <InputLabel sx={{ color: 'var(--text-muted)' }}>Event Type</InputLabel>
                <Select
                  label="Event Type"
                  value={triggerEvent}
                  onChange={e => setTriggerEvent(e.target.value)}
                  sx={selectStyle}
                  MenuProps={{ PaperProps: { sx: { bgcolor: '#1b2436' } } }}
                >
                  <MenuItem value="STAGE_CHANGED">Stage Changed</MenuItem>
                </Select>
              </FormControl>

              {triggerEvent === 'STAGE_CHANGED' && (
                <Box sx={{ p: 2, borderRadius: '12px', bgcolor: 'rgba(255, 255, 255, 0.03)', border: '1px dashed rgba(255, 255, 255, 0.1)' }}>
                  <Typography variant="caption" sx={{ color: 'var(--text-muted)', mb: 1, display: 'block' }}>When stage equals:</Typography>
                  <Select
                    fullWidth
                    size="small"
                    value={triggerStageValue}
                    onChange={e => setTriggerStageValue(e.target.value)}
                    sx={selectStyle}
                    MenuProps={{ PaperProps: { sx: { bgcolor: '#1b2436' } } }}
                  >
                    <MenuItem value="PROSPECTING">Prospecting</MenuItem>
                    <MenuItem value="QUALIFICATION">Qualification</MenuItem>
                    <MenuItem value="PROPOSAL">Proposal</MenuItem>
                    <MenuItem value="NEGOTIATION">Negotiation</MenuItem>
                    <MenuItem value="CLOSED_WON">Closed Won</MenuItem>
                    <MenuItem value="CLOSED_LOST">Closed Lost</MenuItem>
                  </Select>
                </Box>
              )}
            </Paper>
          </Grid>

          {/* Connection Arrow */}
          <Grid item xs={12} md={2} sx={{ display: 'flex', justifyContent: 'center' }}>
            <Box sx={{ 
              width: 48, 
              height: 48, 
              borderRadius: '50%', 
              display: 'flex', 
              alignItems: 'center', 
              justifyContent: 'center',
              bgcolor: 'rgba(255, 255, 255, 0.05)',
              color: 'var(--primary-color)',
              boxShadow: '0 0 20px rgba(124, 105, 239, 0.2)'
            }}>
              <LucideZap size={24} fill="var(--primary-color)" />
            </Box>
          </Grid>

          {/* THEN (Action) */}
          <Grid item xs={12} md={5}>
            <Paper elevation={0} sx={{ 
              p: 4, 
              borderRadius: '24px', 
              bgcolor: 'rgba(16, 185, 129, 0.05)',
              border: '1px solid rgba(16, 185, 129, 0.1)',
              position: 'relative',
              minHeight: 340
            }}>
              <Box sx={{ 
                position: 'absolute', 
                top: -12, 
                left: 24, 
                bgcolor: '#10b981', 
                px: 1.5, 
                py: 0.5, 
                borderRadius: '8px',
                color: 'white',
                fontSize: '0.75rem',
                fontWeight: 800,
                letterSpacing: 1
              }}>
                THEN
              </Box>
              <Typography variant="h6" sx={{ mb: 1, fontWeight: 700 }}>Configure Action</Typography>
              <Typography variant="body2" sx={{ mb: 3, color: 'var(--text-muted)' }}>Choose what happens when the trigger fires.</Typography>

              <FormControl fullWidth sx={{ mb: 3 }}>
                <InputLabel sx={{ color: 'var(--text-muted)' }}>Action Type</InputLabel>
                <Select
                  label="Action Type"
                  value={actionType}
                  onChange={e => setActionType(e.target.value)}
                  sx={selectStyle}
                  MenuProps={{ PaperProps: { sx: { bgcolor: '#1b2436' } } }}
                >
                  <MenuItem value="CREATE_TASK">Create a Task</MenuItem>
                  <MenuItem value="SEND_FCM">Send Push Notification</MenuItem>
                </Select>
              </FormControl>

              {actionType === 'CREATE_TASK' && (
                <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                  <TextField 
                    fullWidth 
                    size="small"
                    label="Task Title" 
                    value={taskTitle}
                    onChange={e => setTaskTitle(e.target.value)}
                    sx={textFieldStyle}
                  />
                  <TextField 
                    fullWidth 
                    size="small"
                    multiline
                    rows={2}
                    label="Task Description" 
                    value={taskDesc}
                    onChange={e => setTaskDesc(e.target.value)}
                    sx={textFieldStyle}
                  />
                </Box>
              )}

              {actionType === 'SEND_FCM' && (
                <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                  <FormControl fullWidth sx={{ mb: 1 }}>
                    <InputLabel sx={{ color: 'var(--text-muted)' }}>Target Type</InputLabel>
                    <Select
                      size="small"
                      label="Target Type"
                      value={fcmTargetType}
                      onChange={e => setFcmTargetType(e.target.value)}
                      sx={selectStyle}
                      MenuProps={{ PaperProps: { sx: { bgcolor: '#1b2436' } } }}
                    >
                      <MenuItem value="TOPIC">Topic</MenuItem>
                      <MenuItem value="TOKEN">Individual Token</MenuItem>
                    </Select>
                  </FormControl>
                  <TextField 
                    fullWidth 
                    size="small"
                    label={fcmTargetType === 'TOPIC' ? "Topic Name" : "Device Token"}
                    placeholder={fcmTargetType === 'TOPIC' ? "e.g., all-users" : "Firebase FCM Token"}
                    value={fcmTargetValue}
                    onChange={e => setFcmTargetValue(e.target.value)}
                    sx={textFieldStyle}
                  />
                  <TextField 
                    fullWidth 
                    size="small"
                    label="Notification Title" 
                    value={fcmTitle}
                    onChange={e => setFcmTitle(e.target.value)}
                    sx={textFieldStyle}
                  />
                  <TextField 
                    fullWidth 
                    size="small"
                    multiline
                    rows={2}
                    label="Notification Body" 
                    value={fcmBody}
                    onChange={e => setFcmBody(e.target.value)}
                    sx={textFieldStyle}
                  />
                </Box>
              )}
            </Paper>
          </Grid>
        </Grid>
      </Box>
    </Box>
  );
};

export default AutomationBuilder;
